### ISSUE TITLE
SPI opens wrong spidev path

### ISSUE THREAD

**Issue by pdp7** [adafruit/adafruit-beaglebone-io-python#216]
## System info:
current Adafruit_BBIO `master` on  Debian 9.2 image with 4.14.2-ti-r13 kernel

## Example:
```python
from Adafruit_BBIO.SPI import SPI

print("SPI(1,0)")
spi = SPI(1,0)
print(spi.xfer2([32, 11, 110, 22, 220]))
spi.close() 

print("SPI(1,1)");
spi = SPI(1,1)
print(spi.xfer2([32, 11, 110, 22, 220]))
spi.close() 

print("SPI(2,0)")
spi = SPI(2,0)
print(spi.xfer2([32, 11, 110, 22, 220]))
spi.close() 

print("SPI(2,1)");
spi = SPI(2,1)
print(spi.xfer2([32, 11, 110, 22, 220]))
spi.close() 
```

## Issue:
* `SPI(1,0)` and `SPI(2,0)` both open `/dev/spidev1.0`
* `SPI(1,1)` and `SPI(2,1)` both open `/dev/spidev1.1`
* However, the actual spidev devices that exist are:
  * /dev/spidev0.0
  * /dev/spidev0.1
  * /dev/spidev1.0
  * /dev/spidev1.1
* These are the /sys/ entries:
```
/sys/devices/platform/ocp/48030000.spi/spi_master/spi0/spi0.0/spidev/spidev0.0/dev
/sys/devices/platform/ocp/48030000.spi/spi_master/spi0/spi0.1/spidev/spidev0.1/dev
/sys/devices/platform/ocp/481a0000.spi/spi_master/spi1/spi1.0/spidev/spidev1.0/dev
/sys/devices/platform/ocp/481a0000.spi/spi_master/spi1/spi1.1/spidev/spidev1.1/dev
```

**Comment by pdp7** [comment]
```diff
diff --git a/source/common.c b/source/common.c
index e8fbbec..64e14e2 100644
--- a/source/common.c
+++ b/source/common.c
@@ -503,29 +503,53 @@ int get_spi_bus_path_number(unsigned int spi)
 {
   char path[MAX_PATH];
 
+  fprintf(stderr, "----------------------------------\n");
+
 #ifdef BBBVERSION41
   strncpy(ocp_dir, "/sys/devices/platform/ocp", sizeof(ocp_dir));
 #else
   build_path("/sys/devices", "ocp", ocp_dir, sizeof(ocp_dir));
 #endif
 
+  fprintf(stderr, "get_spi_bus_path_number(): ocp_dir=%s\n", ocp_dir);
+  fprintf(stderr, "get_spi_bus_path_number(): spi=%d\n", spi);
+
+  /*
+     for Debian 9.2 image with 4.14.2-ti-r13 kernel:
+
+     /sys/devices/platform/ocp/48030000.spi/spi_master/spi0/spi0.0/spidev/spidev0.0/dev
+     /sys/devices/platform/ocp/48030000.spi/spi_master/spi0/spi0.1/spidev/spidev0.1/dev
+     /sys/devices/platform/ocp/481a0000.spi/spi_master/spi1/spi1.0/spidev/spidev1.0/dev
+     /sys/devices/platform/ocp/481a0000.spi/spi_master/spi1/spi1.1/spidev/spidev1.1/dev
+  */
+
   if (spi == 0) {
-      snprintf(path, sizeof(path), "%s/48030000.spi/spi_master/spi1", ocp_dir);
-  } else {
+      snprintf(path, sizeof(path), "%s/48030000.spi/spi_master/spi0", ocp_dir);
+  } else if (spi == 1) {
       snprintf(path, sizeof(path), "%s/481a0000.spi/spi_master/spi1", ocp_dir);
+  } else {
+      return -1;
   }
   
+  fprintf(stderr, "get_spi_bus_path_number(): path=%s\n", path);
   DIR* dir = opendir(path);
   if (dir) {
+      fprintf(stderr, "get_spi_bus_path_number(): dir is true\n");
       closedir(dir);
-      //device is using /dev/spidev1.x
-      return 1;
+      fprintf(stderr, "get_spi_bus_path_number(): device is using /dev/spidev0.x\n");
+      fprintf(stderr, "get_spi_bus_path_number(): return 0\n");
+      return 0;
   } else if (ENOENT == errno) {
-      //device is using /dev/spidev2.x
-      return 2;
+      fprintf(stderr, "get_spi_bus_path_number(): ENOENT\n");
+      fprintf(stderr, "get_spi_bus_path_number(): device is using /dev/spidev1.x\n");
+      fprintf(stderr, "get_spi_bus_path_number(): return 1\n");
+      return 1;
   } else {
+      fprintf(stderr, "get_spi_bus_path_number(): return -1\n");
       return -1;
   }
+
+  fprintf(stderr, "----------------------------------\n");
 }
```

Results:
```
SPI(0,0)
================================
bus=0
device=0
----------------------------------
get_spi_bus_path_number(): ocp_dir=/sys/devices/platform/ocp
get_spi_bus_path_number(): spi=0
get_spi_bus_path_number(): path=/sys/devices/platform/ocp/48030000.spi/spi_master/spi0
get_spi_bus_path_number(): dir is true
get_spi_bus_path_number(): device is using /dev/spidev0.x
get_spi_bus_path_number(): return 0
bus_path=0
path=/dev/spidev0.0
================================
[255, 255, 255, 255, 255]
SPI(0,1)
================================
bus=0
device=1
----------------------------------
get_spi_bus_path_number(): ocp_dir=/sys/devices/platform/ocp
get_spi_bus_path_number(): spi=0
get_spi_bus_path_number(): path=/sys/devices/platform/ocp/48030000.spi/spi_master/spi0
get_spi_bus_path_number(): dir is true
get_spi_bus_path_number(): device is using /dev/spidev0.x
get_spi_bus_path_number(): return 0
bus_path=0
path=/dev/spidev0.1
================================
[255, 255, 255, 255, 255]
SPI(1,0)
================================
bus=1
device=0
----------------------------------
get_spi_bus_path_number(): ocp_dir=/sys/devices/platform/ocp
get_spi_bus_path_number(): spi=1
get_spi_bus_path_number(): path=/sys/devices/platform/ocp/481a0000.spi/spi_master/spi1
get_spi_bus_path_number(): dir is true
get_spi_bus_path_number(): device is using /dev/spidev0.x
get_spi_bus_path_number(): return 0
bus_path=0
path=/dev/spidev0.0
================================
[255, 255, 255, 255, 255]
SPI(1,1)
================================
bus=1
device=1
----------------------------------
get_spi_bus_path_number(): ocp_dir=/sys/devices/platform/ocp
get_spi_bus_path_number(): spi=1
get_spi_bus_path_number(): path=/sys/devices/platform/ocp/481a0000.spi/spi_master/spi1
get_spi_bus_path_number(): dir is true
get_spi_bus_path_number(): device is using /dev/spidev0.x
get_spi_bus_path_number(): return 0
bus_path=0
path=/dev/spidev0.1
================================
[255, 255, 255, 255, 255]
SPI(2,0)
================================
bus=2
device=0
----------------------------------
get_spi_bus_path_number(): ocp_dir=/sys/devices/platform/ocp
get_spi_bus_path_number(): spi=2
Traceback (most recent call last):
  File "/home/debian/spi.py", line 32, in <module>
    spi = SPI(2,0)
OverflowError: Unable to find loaded spi bus path.
```

**Comment by pdp7** [comment]
```diff
SPI(0,0)
================================
bus=0
device=0
path=/dev/spidev0.0
[255, 255, 255, 255, 255]

SPI(0,1)
================================
bus=0
device=1
path=/dev/spidev0.1
[255, 255, 255, 255, 255]

SPI(1,0)
================================
bus=1
device=0
path=/dev/spidev1.0
[255, 255, 255, 255, 255]

SPI(1,1)
================================
bus=1
device=1
path=/dev/spidev1.1
[255, 255, 255, 255, 255]

SPI(2,0)
================================
bus=2
device=0
path=/dev/spidev2.0
Traceback (most recent call last):
  File "/home/debian/spi.py", line 32, in <module>
    spi = SPI(2,0)
IOError: [Errno 2] No such file or directory
```
