### ISSUE TITLE
RE: MotorBridge.py Library from https://github.com/Seeed-Studio/MotorBridgeCapeforBBG_BBB

### ISSUE THREAD

**Issue by silver2row** [adafruit/adafruit-beaglebone-io-python#235]
- Platform/operating system (i.e. Raspberry Pi with Raspbian operating system,
  Windows 32-bit, Windows 64-bit, Mac OSX 64-bit, etc.):  **BeagleBone Green on PuTTY/Win w/ a Debian OS/kernel 4.9.x**

- Python version (run `python -version` or `python3 -version`):  **python 2.7.13**

- Error message you are receiving, including any Python exception traces:  **more on this below...**

- List the steps to reproduce the problem below (if possible attach code or commands
  to run): **LIST REPRO STEPS BELOW**

**When I run this software w/ sudo python mbcUse.py, I get specific errors that seem to be well understood but are not descriptive enough.**

    import MotorBridge
    import time

    MotorName        = 1
    MotorName        = 2
    ClockWise        = 1
    CounterClockWise = 2
    PwmDuty          = 90
    Frequency        = 1000

    if __name__=="__main__":
        motor = MotorBridge.MotorBridgeCape()
        motor.DCMotorInit(1, 1000)
        motor.DCMotorInit(2, 1000)
        for i in range(1, 51):
            motor.DCMotorMove(1, 1, 90)
            motor.DCMotorMove(2, 1, 90)
            print "I got your biscuit, now!"
  
    #Making a U-Shape in the lawn
    #Left motor on chassis goes while the right motor ccw
        motor = MotorBridge.MotorBridgeCape()
        motor.DCMotorInit(1, 1000)
        motor.DCMotorInit(2, 1000)
        for i in range(1, 3):
            motor.DCMotorMove(1, 1, 90)
            motor.DCMotorMove(2, 2, 90)
            print "I love Jim's TURN!"

    #All Flanks...Straight Ahead!        
        motor = MotorBridge.MotorBridgeCape()
        motor.DCMotorInit(1, 1000)
        motor.DCMotorInit(2, 1000)
        for i in range(1, 51):
            motor.DCMotorMove(1, 1, 90)
            motor.DCMotorMove(2, 1, 90)
            print "Give in to temptation!"
        
    #Make another U-Turn but this time, motors go in the opposite direction!
        motor = MotorBridge.MotorBridgeCape()
        motor.DCMotorInit(1, 1000)
        motor.DCMotorInit(2, 1000)
        for i in range(1, 3):
            motor.DCMotorMove(1, 2, 90)
            motor.DCMotorMove(2, 1, 90)
        
    #Straight Ahead
        motor = MotorBridge.MotorBridgeCape()
        motor.DCMotorInit(1, 1000)
        motor.DCMotorInit(2, 1000)
        for i in range(1, 51):
            motor.DCMotorMove(1, 1, 90)
            motor.DCMotorMove(2, 1, 90)
            print "Tacos are not all around here!"
        
        motor = MotorBridge.MotorBridgeCape()
        motor.DCMotorInit(1, 1000)
        motor.DCMotorInit(2, 1000)
        for i in range(1, 3):
            motor.DCMotorMove(1, 1, 90)
            motor.DCMotorMove(2, 2, 90)
    
        motor = MotorBridge.MotorBridgeCape()
        motor.DCMotorInit(1, 1000)
        motor.DCMotorInit(2, 1000)
        for i in range(1, 51):
            motor.DCMotorMove(1, 1, 90)
            motor.DCMotorMove(2, 1, 90)    
    
        motor = MotorBridge.MotorBridgeCape()
        motor.DCMotorInit(1, 1000)
        motor.DCMotorInit(2, 1000)
        for i in range(1, 3):
            motor.DCMotorMove(1, 2, 90)
            motor.DCMotorMove(2, 1, 90)
    
        motor = MotorBridge.MotorBridgeCape()
        motor.DCMotorInit(1, 1000)
        motor.DCMotorInit(2, 1000)
        for i in range(1, 51):
            motor.DCMotorMove(1, 1, 90)
            motor.DCMotorMove(2, 1, 90)

        motor = MotorBridge.MotorBridgeCape()
        motor.DCMotorInit(1, 1000)
        motor.DCMotorInit(2, 1000)
        for i in range(1, 3):
            motor.DCMotorMove(1, 1, 90)
            motor.DCMotorMove(2, 2, 90)

        motor = MotorBridge.MotorBridgeCape()
        motor.DCMotorInit(1, 1000)
        motor.DCMotorInit(2, 1000)
        for i in range(1, 51):
            motor.DCMotorMove(1, 1, 90)
            motor.DCMotorMove(2, 1, 90)        

        motor = MotorBridge.MotorBridgeCape()
        motor.DCMotorInit(1, 1000)
        motor.DCMotorInit(2, 1000)
        for i in range(1, 3):
            motor.DCMotorMove(1, 2, 90)
            motor.DCMotorMove(2, 1, 90)
        
        motor = MotorBridge.MotorBridgeCape()
        motor.DCMotorInit(1, 1000)
        motor.DCMotorInit(2, 1000)
        for i in range(1, 51):
            motor.DCMotorMove(1, 1, 90)
            motor.DCMotorMove(2, 1, 90)
            print "Major Malfunction!"

W/ Adafruit_BBIO as my I2C library and this Motor Bridge Cape library typed up in Python from this site: https://github.com/Seeed-Studio/MotorBridgeCapeforBBG_BBB, I get errors: **Please see the MotorBridge.py library below**.

**https://github.com/Seeed-Studio/MotorBridgeCapeforBBG_BBB/blob/master/BBG_MotorBridgeCape/MotorBridge.py** was the original software library typed in Python that I have been using until more recently when the I2C library changed a bit from the Adafruit_BBIO libraries. I took some time off of the BBB/BBG, and etc, to not use my target boards.

Anyway, I would git clone "Seeed-Studio/MotorBridgeCapeforBBG_BBB/BBG_MotorBridgeCape to get the MotorBridge.py library. After getting that library, I would alter the MotorBridge.py file/library to suit my needs, i.e. just like now. 

I have been unable to produce working scripts/software w/ the Motor Bridge Cape, Adafruit_BBIO for I2C functionality, and the BBG w/ a Debian Distro w/ kernel 4.9.x.

This is my change in the MotorBridge.py library w/ corresponding errors listed below the change in the library:

    from Adafruit_GPIO.I2C import Adafruit_GPIO.I2C
    import Adafruit_GPIO.I2C as I2C
    import Adafruit_GPIO as GPIO
    import time
    Reset = "P9_23"
    MotorBridge = Adafruit_GPIO.I2C(0x49)
    GPIO.setup(Reset, GPIO.OUT)

I receive this issue:

    Traceback (most recent call last):
      File "mbcUse.py", line 1, in <module>
        import MotorBridge
      File "/home/debian/MotorBridgeCapeforBBG_BBB/BBG_MotorBridgeCape/MotorBridge.py", line 33
        from Adafruit_GPIO.I2C import Adafruit_GPIO.I2C
                                                                              ^
    SyntaxError: invalid syntax

When I change the MotorBridge.py library to this:

    import Adafruit_GPIO.I2C as I2C
    import Adafruit_GPIO as GPIO
    import time
    Reset = "P9_23"
    MotorBridge = Adafruit_GPIO.I2C(0x49)
    GPIO.setup(Reset, GPIO.OUT)

I receive this error code:

    Traceback (most recent call last):
      File "mbcUse.py", line 1, in <module>
        import MotorBridge
      File "/home/debian/MotorBridgeCapeforBBG_BBB/BBG_MotorBridgeCape/MotorBridge.py", line 37, in 
    <module>
        MotorBridge = Adafruit_GPIO.I2C(0x49)
    NameError: name 'Adafruit_GPIO' is not defined

So...in hindsight, I see that all my alterations have been disallowed in Python so far. I have changed the software library for the MotorBridge.py file many times, each w/ different software strokes, to no avail w/ my current configuration on my system. 

If this gets too boring, let me know. I will shorten my typing.

Seth

P.S. If you have any commands to give, please shoot me a couple of lines. Thank you for anyone willing to read this post. Oh and if you are willing to sit and listen, I will tell you all the avenues I took to produce the changes in the MotorBridge.py library and the respective error codes and syntax errors (many derivatives).

**Comment by silver2row** [comment]
Hello,

Just for reference, I was using the Cape w/ the BBG in the past to run a self-propelled mower (of sorts). It would run like this:

    >>>>>>>>>>>
    <<<<<<<<<<<^
    >>>>>>>>>>>^

It would run like a forward, u-turn one direction, forward to where it started on another section of yard, u-turn another direction, and start over until completed.

Seth

P.S. I think this makes sense. I have other target boards, BBGW and BBB respectively, that run this Cape and work just fine. I am basically testing this board to see if the Cape will work w/ updated u-boot tech. and updated kernels/images.

**Comment by silver2row** [comment]
Hello and More Info,

uname -r

    4.9.82-ti-r102

cat /etc/dogtag

    BeagleBoard.org Debian Image 2018-02-18

sudo ./version.sh | grep bootloader

    bootloader:[microSD-(push-button)]:[/dev/mmcblk0]:[U-Boot 2018.01-00002-g60ae27e116]:[location: 
    dd MBR]

Seth

**Comment by silver2row** [comment]
Hello Again,

I received an error a while back. This may be of some concern w/ this MotorBridgeCape and the library, i.e. MotorBridge.py. 

writeList was not part of the I2C library from Adafruit_BBIO. This may have changed in the newer version of Adafruit_BBIO, i.e. version 1.0.10.

Seth

P.S. I will test some workaround or change software to see where I get. I will be back. Thank you again. For anyone reading these posts, thank you if you are utilizing the Motor Bridge Cape and MotorBridge.py library.

**Comment by silver2row** [comment]
Hello Once More,

If this issue pertains to another software source, please let me know. I can and will close this "comment" if the subject pertains to other software.

Seth
