### ISSUE TITLE
Can't Set Encoder Frequency Using Python3

### ISSUE THREAD

**Issue by pdp7** [adafruit/adafruit-beaglebone-io-python#299]
From the Adafruit forum:
https://forums.adafruit.com/viewtopic.php?f=49&t=145110&p=716829#p716829

Test:
```
from Adafruit_BBIO.Encoder import RotaryEncoder, eQEP2

test_encoder = RotaryEncoder(eQEP2)

# Enable
test_encoder.enable()

# Attempt to set frequency
test_encoder.frequency = 2000

print(test_encoder.frequency)

# Disable
test_encoder.disable()
```

Error:
```
ebian@beaglebone:~$ python encoder_test.py
2000
debian@beaglebone:~$ python3 encoder_test.py
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "encoder_test.py", line 9, in <module>
    test_encoder.frequency = 2000
  File "/usr/local/lib/python3.5/dist-packages/Adafruit_BBIO/Encoder.py", line 355, in frequency
    self._eqep.node.period = str(period)
  File "/usr/local/lib/python3.5/dist-packages/Adafruit_BBIO/sysfs.py", line 93, in __setattr__
    fp.write(val)
OSError: [Errno 22] Invalid argument
```

**Comment by pdp7** [comment]
update:
> If it's of any help I've attached the strace output of the initial code executed with python 2 for comparison. 
> 
> Looking at that write() call, the main difference I see is that Python3 is trying to write a float ("500000.0") while Python2 is not ("500000"). Not sure if the driver expects a certain type.

**Comment by pdp7** [comment]
update:
> I've been able to confirm that that's the issue. It stems from how Python3 handles division as discussed here https://stackoverflow.com/questions/49282799/python-3-int-division-operator-is-returning-a-float.
> 
> I tested this by explicitly casting the period to an int in the frequency setter of Encoder.py and the program executed successfully

**Comment by pdp7** [comment]
Link to image with the code fix:
https://forums.adafruit.com/download/file.php?id=63277

**Comment by pdp7** [comment]
Fixed by commit https://github.com/adafruit/adafruit-beaglebone-io-python/commit/b2a6be54a102377b8e1a5018948362b07e71adc3

**test299.py**
```
from Adafruit_BBIO.Encoder import RotaryEncoder, eQEP2

test_encoder = RotaryEncoder(eQEP2)

# Enable
test_encoder.enable()

# Attempt to set frequency
test_encoder.frequency = 2000

print(test_encoder.frequency)

# Disable
test_encoder.disable()
```
```
debian@beaglebone:~$ python3 test299.py 
2000.0
```
