### ISSUE TITLE
Compile issues with pyinstaller

### ISSUE THREAD

**Issue by CBXstraight6** [adafruit/adafruit-beaglebone-io-python#98]
Trying to compile my code using pyinstaller, which reports & compiles without issue, but when I try to execute / run the compiled code I get this message
>>
Traceback (most recent call last):
  File "Concentrator.py", line 34, in <module>
  File "/tmp/pip-build-e2yxaF/pyInstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "build/bdist.linux-armv7l/egg/Adafruit_BBIO/UART.py", line 7, in <module>
  File "build/bdist.linux-armv7l/egg/Adafruit_BBIO/UART.py", line 6, in __bootstrap__
ImportError: /tmp/_MEIE8WnrP/Adafruit_BBIO/UART.so: cannot open shared object file: No such file or directory
>>
Is anyone able to throw some light on what has gone wrong and/or how to resolve it.
Thanks,
AJ

**Comment by pdp7** [comment]
@CBXstraight6  There were several improvement in #108. Please check if this is still an issue.
